language: minimal

services:
  - docker

git:
  depth: false
  quiet: true

install:
  - |
    docker build \
    -f core/Dockerfile  \
    --target CI  \
    -t learn-hub-web-server:test \
    core  # Building the repo CI test image
  - docker pull postgres:12
  - |
    docker container run -d \
    --env POSTGRES_USER=${POSTGRES_USER} \
    --env POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
    --env POSTGRES_DB=${POSTGRES_DB} \
    --name postgres_db postgres
  - |
    export POSTGRES_HOST="$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' postgres_db)"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mkdir coverage/
  - |
    docker container run -t learn-hub-web-server:test \
    black .
  - |
    docker container run -t learn-hub-web-server:test \
    flake8 .
  - |
    docker container run -t \
    --env POSTGRES_USER=${POSTGRES_USER} \
    --env POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
    --env POSTGRES_DB=${POSTGRES_DB} \
    --env POSTGRES_HOST=${POSTGRES_HOST} \
    --volume "$PWD/coverage:/usr/src/app/coverage" \
    --name web-server learn-hub-web-server:test \
    pytest
  - ls -alh
  - ls -alh coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./cc-test-reporter after-build -d -p coverage -t coverage.py
